name: 'Compile for Chrome'

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Extract Version'
        id: get_version
        run: |
          VERSION=$(jq -r '.version' src/main/manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: Osprey-${{ env.VERSION }}-chrome
          path: src/main
